import { Helmet } from 'react-helmet-async'
import type { ReactElement } from 'react'
import { IS_INDEXABLE, SITE_URL as BASE_URL } from '@/lib/site'

const SITE_NAME = 'Nice Touch'
/** Fallback share image (generated by scripts/generate-og-images.mjs). */
const DEFAULT_OG_IMAGE = '/og/default.png'
const DEFAULT_OG_IMAGE_ALT = 'Nice Touch — not every part of the edit needs an editor. Done inside Premiere Pro and DaVinci Resolve.'

interface SEOProps {
  title: string
  description: string
  path: string
  /**
   * Path under `/public` (e.g. `/og/transcribe.png`) or an absolute URL.
   * Defaults to the site-wide share image.
   */
  image?: string
  imageAlt?: string
  /** Encourage Google to use a large image preview in SERPs. */
  largeImagePreview?: boolean
  /** Exclude the page from search indexes (e.g. the 404 page). */
  noindex?: boolean
  /** Origins to preconnect (DNS + TLS handshake) for this page only. */
  preconnect?: string[]
  structuredData?: Record<string, unknown> | Record<string, unknown>[]
  /** Set false to suppress the auto-generated BreadcrumbList (e.g. when the page supplies its own). */
  breadcrumb?: boolean
}

function absoluteUrl(value: string): string {
  if (/^https?:\/\//i.test(value)) return value
  return `${BASE_URL}${value.startsWith('/') ? '' : '/'}${value}`
}

export default function SEO({
  title,
  description,
  path,
  image = DEFAULT_OG_IMAGE,
  imageAlt,
  largeImagePreview,
  noindex,
  preconnect,
  structuredData,
  breadcrumb = true,
}: SEOProps): ReactElement {
  const fullTitle = path === '/' ? `${SITE_NAME} — Faster rough cuts in Premiere Pro & DaVinci Resolve` : `${title} | ${SITE_NAME}`
  // Sevalla pretty URLs serve every non-root route with a trailing slash
  // (e.g. /pricing 301s to /pricing/). Canonical + og:url must match the
  // actually-served URL, otherwise the canonical points at a redirect.
  const url = path === '/' ? `${BASE_URL}/` : `${BASE_URL}${path}/`
  const imageUrl = absoluteUrl(image)
  const resolvedImageAlt = imageAlt ?? (image === DEFAULT_OG_IMAGE ? DEFAULT_OG_IMAGE_ALT : undefined)

  const schemas: Record<string, unknown>[] = structuredData
    ? Array.isArray(structuredData)
      ? [...structuredData]
      : [structuredData]
    : []

  // Non-production origins are noindex site-wide, which overrides the per-page
  // hints. Helmet keeps only one meta per name, so this has to resolve to a
  // single value rather than two competing tags.
  const robots = !IS_INDEXABLE
    ? 'noindex, nofollow'
    : noindex
      ? 'noindex'
      : largeImagePreview
        ? 'max-image-preview:large'
        : undefined

  const hasBreadcrumb = schemas.some((s) => s['@type'] === 'BreadcrumbList')
  if (breadcrumb && !hasBreadcrumb && path !== '/' && path !== '/404') {
    schemas.push({
      '@context': 'https://schema.org',
      '@type': 'BreadcrumbList',
      itemListElement: [
        { '@type': 'ListItem', position: 1, name: 'Home', item: `${BASE_URL}/` },
        { '@type': 'ListItem', position: 2, name: title, item: url },
      ],
    })
  }

  return (
    <Helmet>
      <title>{fullTitle}</title>
      <meta name="description" content={description} />
      {!noindex && <link rel="canonical" href={url} />}

      {robots && <meta name="robots" content={robots} />}

      {preconnect?.map((origin) => (
        <link key={origin} rel="preconnect" href={origin} crossOrigin="" />
      ))}

      <meta property="og:title" content={fullTitle} />
      <meta property="og:description" content={description} />
      <meta property="og:url" content={url} />
      <meta property="og:type" content="website" />
      <meta property="og:site_name" content={SITE_NAME} />
      <meta property="og:locale" content="en_GB" />
      <meta property="og:image" content={imageUrl} />
      <meta property="og:image:width" content="1200" />
      <meta property="og:image:height" content="630" />
      {resolvedImageAlt && <meta property="og:image:alt" content={resolvedImageAlt} />}

      <meta name="twitter:card" content="summary_large_image" />
      <meta name="twitter:title" content={fullTitle} />
      <meta name="twitter:description" content={description} />
      <meta name="twitter:image" content={imageUrl} />
      {resolvedImageAlt && <meta name="twitter:image:alt" content={resolvedImageAlt} />}

      {/* One script per schema object — some validators reject top-level arrays. */}
      {schemas.map((schema, i) => (
        <script key={i} type="application/ld+json">
          {JSON.stringify(schema)}
        </script>
      ))}
    </Helmet>
  )
}
